project_id = "zpskukvdzlurrbqlgtuu"

[functions.google-auth]
verify_jwt = false

[functions.google-calendar]
verify_jwt = true

[functions.cleanup-orphan-receivables]
verify_jwt = false

[functions.delete-conta-receber]
verify_jwt = false